### PR TITLE
Feat/governance

### PR DESCRIPTION
**Pull request by JarbasAl**
doc about governance, based on the notes created on our early days

### CODE REVIEW

**Comment by JarbasAl** [comment]
BDFL here is just a word play for the humorous nature of the document, it basically means maintainer, the person taking responsibility for the project

just want to point out this document would essentially apply per repository, if you create a repo under OpenVoiceOS it is still your repo and your project, you are the BDFL, if you leave a project you should nominate a new maintainer, if you dont then OpenVoiceOS members should take it over or archive it or pull out an announcement to the community

**Comment by NeonDaniel** [comment]
I think this document might deserve a rewrite given the current state of the project (important to note that at the time of writing "ovos" was basically HolmesV and Buildroot). I would simplify this and make it more generic.

# Open Voice Governance Guidelines

OVOS is a community project dedicated to building an open source voice assistant and related technologies. This is not a contract, charter, or legal document of any kind but is how the OVOS organization and its members strive to interact with each other.

1) All projects under the organization will be licensed according to our Open Source Licensing Guidelines (LINK HERE)
1) All collaborators will treat each other respectfully
1) Unless specifically noted, a repository administrator has final say over what may and may not be included in a project. In the event that there are multiple administrators that are unable to reach a consensus, a simple majority vote among administrators will determine if a change is accepted or not.
    > Note that this should be extremely uncommon, as there should be some solution that satisfies everyone.
1) Proposed changes, roadmaps, or other short-term goals will be made public prior to adoption to allow for community input and to provide adequate notice for community developers to  plan around.
1) Every reasonable effort will be made to accommodate users. OVOS maintainers are responsible for reviewing user issues and changes.

TODO:
- Add some note about dealing with features that have complex implementations roadmapped with simple solutions available/in a PR
-  Add some note about duplicated/conflicting implementations of a feature (something to the effect of "support any working implementation if it adds functionality, keeping in mind that it may be replaced by a better version in the future")

**Comment by NeonDaniel** [comment]
> * Quantify the relationship between “Cabal” members and the projects they maintain

I think this may be worth a separate doc if we want to specify any specific members/orgs. IMO a "governance" doc should be agnostic so it doesn't have to be updated as collaborators come and go

> * Quantify the central Things

Would this not just be any repository under the organization? Again, I think intentional ambiguity allows us to not have to update this whenever something is added to the org/project.

> * Qualify the Cabal’s role in maintaining compat, harmonizing project planning, roadmaps, and so forth

I think my (4) above could be extended, but again I left it vague because we don't have any kind of workflow for that currently.

> * Specify the existence of Collaborators (devs who work on our projects with privs, mostly on GitHub) and Helpers (chat and forum magicians)
> * Specify that community-staffed projects should be run like we’ve tried to run all our projects in the past, just in miniature: the maintainer(s) look for consensus, and turn to votes when it gets contentious, or appeal to the broader community for input if appropriate

Regarding these 2 points, the draft I shared did specify "repository admins" specifically, to not imply that a repo administrator (the "Cabal" members in the initial doc) is responsible.

> * Specify that the maintainer(s) of a project are responsible for staffing it with enough capable Collaborators and Helpers to keep it from going stale, and to avoid self-merging, and to keep it documented, and so that someone is prepared to take over if they get hit by a bus (or take an unscheduled sabbatical of unspecified length)

I agree there should be some note about what happens here

> 
> I have a couple more thoughts, but since I’m typing this in a mobile browser with reckless abandon, I’m gonna stop tempting fate and hit save.

I'll update the PR with my proposed draft so we can collab better. This is going to get worse before it gets better in terms of readability, but I think it has to be done...

**Comment by ChanceNCounter** [comment]
>> Quantify the relationship between “Cabal” members and the projects they maintain

> I think this may be worth a separate doc if we want to specify any specific members/orgs. IMO a "governance" doc should be agnostic so it doesn't have to be updated as collaborators come and go

I don’t mean who, so much as how. There are competing interests at play here. Any given project under the org’s purview is wrapped up in others, so it’s important to everyone that everyone else is managing their projects for everyone’s sake. However, @aiix and @jarbasal have pointed out both that many of us left MycroftAI behind in order to regain some control, and that the feeling of being unable to work on our own software has caused conflict within and without over the years.

>> Quantify the central Things  
> Would this not just be any repository under the organization?

I think the *central* things are the outermost projects, things we might call products if we were a business. OpenVoiceOS is a Thing. The assistant, regarded as such, is a Thing. HiveMind, should development pick back up, is a Thing. There might be more worth labeling, and more might later arise. What I wanted to emphasize is that these are the main things, which the other things are part of/extend/are built on/etc. These are the really big things, too big to say “I’ll manage this one and you’ll manage that one.”

> I think my (4) above could be extended, but again I left it vague because we don't have any kind of workflow for that currently.

I know. I’d very much like to introduce it now, while we’re talking structure, because there’s about to be an influx of users. I’d like to codify all that before we need it, so we can refer to it when we inevitably do.

**Review by 5trongthany — COMMENTED** [review]
I am in favor of Danial's simplified version of the docs. I think being a relatively small project and this being an overarching governance doc, keeping the language simple and the rules open helps us better adapt as we grow & change without having to rewrite our governance docs.

**Comment by ChanceNCounter** [comment]
This conversation has been superseded by the process of writing our Articles of Incorporation. It's likely that the structure of the open source operation itself will ultimately be covered either through bylaws or through some other governing document to be passed by the Board after incorporation, but, in any event, this one has clearly gone stale.

**Comment by JarbasAl** [comment]
as a final comment I just want to point out the aim of this document was to give MORE power to the team, the goal was to share more decision making power than that provided in a standard maintainer role

as is, the default FOSS status quo for each repo holds, the author is the maintainer and has full decision making power over the repo, note that what this document called a BDFL had less power than a author/maintainer has by default, no agreement was reached and this doc is now a historical reference only

The formation of the foundation and the Articles of Incoportation and bylaws will define any changes to this status quo moving forward

**Pull request closed without merging**
